language: python
python: "2.7.10"
services:
        - mongodb
addons:
        apt:
                sources:
                - mongodb-3.0-precise
                packages:
                - mongodb-org-server
install: "pip install -r src/server/requirements.txt"
script:
        - cd src/server/__tests__
        - ./run_tests.sh
